- name: UFW allow http
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: UFW allow https
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Copy docker folder
  copy:
    src: ./docker
    dest: ~/

- name: Generate .env file for docker-compose
  template:
    src: traefik.env.j2
    dest: ~/docker/traefik

- name: Run docker compose traefik
  community.docker.docker_compose_v2:
    project_src: ~/docker/traefik
    state: present

- name: Run docker compose app1
  community.docker.docker_compose_v2:
    project_src: ~/docker/app1
    state: present

- name: Run docker compose app2
  community.docker.docker_compose_v2:
    project_src: ~/docker/app2
    state: present
