- name: Docker SDK for python
  become: true
  package:
    name: python3-docker
    state: present

- name: UFW allow http
  become: true
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: UFW allow https
  become: true
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Swarm init
  become: true
  community.docker.docker_swarm:
    state: present

- name: Copy docker folder
  copy:
    src: ./docker
    dest: ~/

- name: Generate traefik compose file
  template:
    src: traefik-compose.yaml.j2
    dest: ~/docker/traefik/docker-compose.yaml

- name: Create traefik network
  become: true
  community.docker.docker_network:
    name: traefik-net
    driver: overlay
    attachable: true
    state: present

- name: Run treafik stack
  command: docker stack deploy --compose-file ~/docker/traefik/docker-compose.yaml --detach=true traefik

- name: Run example app stack
  command: docker stack deploy --compose-file ~/docker/apps/example-app/docker-compose.yaml --detach=true example-app
