- name: Docker SDK for python
  package:
    name: python3-docker
    state: present

- name: Jsondiff
  package:
    name: python3-jsondiff
    state: present

- name: UFW allow http
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: UFW allow https
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Swarm init
  community.docker.docker_swarm:
    state: present

- name: Copy docker folder
  copy:
    src: ./docker
    dest: ~/

- name: Generate .env file for docker-compose
  template:
    src: traefik.env.j2
    dest: ~/docker/traefik

- name: Create treafik network
  community.docker.docker_network:
    name: traefik-net
    driver: overlay
    attachable: true
    state: present

- name: Run docker compose traefik
  community.docker.docker_compose_v2:
    project_src: ~/docker/traefik
    state: present

- name: Run Deploy app1
  community.docker.docker_stack:
    state: present
    name: app1
    compose:
      - /root/docker/app1/docker-compose.yaml
# - name: Run docker compose app2
#   community.docker.docker_compose_v2:
#     project_src: ~/docker/app2
#     state: present

