name: lkwdeploy
description: deploy with lkw

inputs:
  cloudflare-token:
    description: "Cloudflare token"
    required: true
  server-ip:
    description: "Server ip"
    required: true
  ssh-user:
    description: "Ssh user"
    required: true
  ssh-private-key:
    description: "Ssh private key"
    required: true
  config:
    description: "Path to config file"
    required: false
    default: lkw.yaml

runs:
  using: "composite"
  steps:
    - name: Ssh
      uses: webfactory/ssh-agent@v0.10.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - name: Known hosts
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ inputs.server-ip }} >> ~/.ssh/known_hosts
    - name: Install lkw
      shell: bash
      run: |
        curl -L https://github.com/medvesek/infrastructure/releases/latest/download/lkw -o /usr/local/bin/lkw
        chmod +x /usr/local/bin/lkw
    - name: Run lkw
      shell: bash
      env:
        LKW_CLOUDFLARE_TOKEN: ${{ inputs.cloudflare-token }}
        LKW_SERVER_IP: ${{ inputs.server-ip }}
        LKW_SSH_USER: ${{ inputs.ssh-user }}
      run: |
        lkw deploy --config ${{ inputs.config }}
