- name: UFW allow SSH
  become: yes
  ufw:
    rule: allow
    name: OpenSSH

- name: UFW enable
  become: yes
  ufw:
    state: enabled

- name: Install pip
  become: true
  package:
    name: python3-pip
    state: present

- name: Install pipx
  become: true
  package:
    name: pipx
    state: present

- name: Configure pipx
  command: pipx ensurepath

- name: Dotenv
  community.general.pipx:
    name: dotenv-cli
    state: absent
