- name: Set vars
  set_fact:
    app_dir: "{{ ansible_env.HOME }}/docker/apps/{{ app_name }}"
    deploy_command: |
      dotenv docker stack deploy 
      --compose-file docker-compose.yml 
      --compose-file override.yml 
      --detach=false 
      --prune 
      {{ app_name }}

- name: python3-dotenv-cli
  become: true
  package:
    name: python3-dotenv-cli
    state: present

- name: Copy files
  synchronize:
    src: "{{ source }}/"
    dest: "{{ app_dir }}"
    mode: push
    delete: yes

- name: Generate override
  template:
    src: override.yml.j2
    dest: "{{ app_dir }}/override.yml"
    lstrip_blocks: true

- name: Check if stack already exists
  command: docker stack ps {{ app_name }}
  register: output_check_stack_exists
  failed_when: output_check_stack_exists.rc not in [0,1]

- name: Deploy if not exists
  when: output_check_stack_exists.rc == 1
  command: "{{ deploy_command }}"
  args:
    chdir: "{{ app_dir }}"

- name: Run pre deploy commands
  include_tasks: predeploy.yml
  loop: "{{ pre_deploy }}"

- name: Deploy
  when: output_check_stack_exists.rc == 0
  command: "{{ deploy_command }}"
  args:
    chdir: "{{ app_dir }}"
