- name: Generate .env file for docker-compose
  template:
    src: ./docker/traefik/.env.j2
    dest: ./docker/traefik/env.j2

- name: Copy docker folder
  copy:
    src: ./docker
    dest: ~/

- name: Run docker compose traefik
  community.docker.docker_compose_v2:
    project_src: ~/docker/traefik
    state: present

- name: Run docker compose app1
  community.docker.docker_compose_v2:
    project_src: ~/docker/app1
    state: present

- name: Run docker compose app2
  community.docker.docker_compose_v2:
    project_src: ~/docker/app2
    state: present
