- name: Aquila
  hosts: aquila
  roles:
    - role: common
    - role: appserver
      vars:
        traefik_basic_auth: "{{ lookup('env', 'TRAEFIK_BASIC_AUTH') }}"
        my_email: "{{ lookup('env', 'MY_EMAIL') }}"
    - role: mailserver
      vars:
        emails:
          - ajmuht.eu
          - cmrlj.eu
        forward_to: "{{ lookup('env', 'MY_EMAIL') }}"
