- name: Aquila
  hosts: aquila
  roles:
    - role: common
    - role: appserver
      vars:
        traefik_basic_auth: "{{ lookup('env', 'TRAEFIK_BASIC_AUTH') }}"
        my_email: "{{ lookup('env', 'MY_EMAIL') }}"
    - role: mailserver
      vars:
        emails:
          - ajmuht.eu
          - cmrlj.eu
        forward_to: "{{ lookup('env', 'MY_EMAIL') }}"
  tasks:
    - name: Uninstall netdata
      shell: curl https://get.netdata.cloud/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --disable-telemetry --claim-token {{ lookup('env', 'NETDATA_CLAIM_TOKEN') }} --uninstall
