- name: Aquila
  hosts: aquila
  roles:
    - common
    - geerlingguy.docker
    - role: geerlingguy.postfix
      vars:
        postfix_service_state: started
        postfix_service_enabled: true
        postfix_inet_interfaces: all
        postfix_inet_protocols: all
  tasks:
    - name: UFW allow mail
      become: yes
      ufw:
        rule: allow
        name: Postfix

    - name: UFW allow http
      become: yes
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: UFW allow https
      become: yes
      ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Copy docker folder
      copy:
        src: ./docker
        dest: ~/

    - name: Run docker compose traefik
      community.docker.docker_compose_v2:
        project_src: ~/docker/traefik
        state: present

    - name: Run docker compose app1
      community.docker.docker_compose_v2:
        project_src: ~/docker/app1
        state: present

    - name: Run docker compose app2
      community.docker.docker_compose_v2:
        project_src: ~/docker/app2
        state: present

    - name: Postfix main.cf
      lineinfile:
        path: /etc/postfix/main.cf
        regexp: "^virtual_alias_domains ="
        line: virtual_alias_domains = cmrlj.eu ajmuht.eu

    - name: Postfix main.cf
      lineinfile:
        path: /etc/postfix/main.cf
        regexp: "^virtual_alias_maps ="
        line: virtual_alias_maps = hash:/etc/postfix/virtual

    - name: Postfix virtual
      copy:
        dest: /etc/postfix/virtual
        content: |
          @cmrlj.eu	{{ lookup("env", "MY_EMAIL") }}
          @ajmuht.eu	{{ lookup("env", "MY_EMAIL") }}

    - name: Postfix postmap
      command: postmap /etc/postfix/virtual

    - name: Postfix reload
      command: postfix reload
