- name: Aquila
  hosts: aquila
  roles:
    - role: common
    - role: appserver
      vars:
        traefik_basic_auth: "{{ lookup('env', 'TRAEFIK_BASIC_AUTH') }}"
        my_email: "{{ lookup('env', 'MY_EMAIL') }}"
    - role: mailserver
      vars:
        emails:
          - ajmuht.eu
          - cmrlj.eu
        forward_to: "{{ lookup('env', 'MY_EMAIL') }}"
  tasks:
    - name: Install netdata
      command: wget -O /tmp/netdata-kickstart.sh https://get.netdata.cloud/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token {{ lookup("env", "NETDATA_CLAIM_TOKEN") }}
