- name: My first play
  hosts: all
  roles:
    - geerlingguy.docker
    - geerlingguy.postfix
  tasks:
    - name: UFW enable SSH
      become: yes
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW enable mail
      become: yes
      ufw:
        rule: allow
        name: Postfix

    - name: UFW enable
      become: yes
      ufw:
        state: enabled

    - name: Copy docker-compose
      copy:
        src: ./docker-compose.yaml
        dest: ~/docker-compose.yaml

    - name: Run docker compose
      community.docker.docker_compose_v2:
        project_src: ~/
        project_name: my_project
        state: present

    - name: Postfix main.cf
      lineinfile:
        path: /etc/postfix/main.cf
        line: virtual_alias_domains = localhost

    - name: Postfix main.cf
      lineinfile:
        path: /etc/postfix/main.cf
        line: virtual_alias_maps = hash:/etc/postfix/virtual

    - name: Postfix virtual
      copy:
        dest: /etc/postfix/virtual
        content: |
          @cmrlj.eu	{{ lookup("env", "MY_EMAIL") }}

    - name: Postfix postmap
      command: postmap /etc/postfix/virtual

    - name: Postfix reload
      command: postfix reload
