name: Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - master

env:
  MY_EMAIL: ${{ secrets.MY_EMAIL }}
  TRAEFIK_BASIC_AUTH: ${{ secrets.TRAEFIK_BASIC_AUTH }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    outputs:
      aquila_ip: ${{ steps.output.outputs.aquila_ip }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: update
        run: sudo apt-get update
      - name: jq
        run: sudo apt-get install jq

      - name: Init
        run: terraform init

      - name: Apply
        run: terraform apply --auto-approve

      - name: Output
        id: output
        run: echo "aquila_ip=$(terraform output -json servers | jq -r '.aquila')" >> $GITHUB_OUTPUT

  ansible:
    needs: terraform
    runs-on: ubuntu-latest
    container: ghcr.io/medvesek/infrastructure-ansible:latest
    defaults:
      run:
        working-directory: ./ansible
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE_GITHUB_ACTIONS }}

      - name: Prepare inventory
        shell: bash
        run: echo -e "[aquila]\n${{ needs.terraform.outputs.aquila_ip }}" > inventory.ini

      - name: Prepare env files
        shell: bash
        # Finds all .env.example files and replaces all values in them with corresponding
        # values from the environment
        run: |
          find . -name '.env.example' | while read file; do
          dir=$(dirname "$file")
          out="${dir}/.env"
          >"$out"
          while IFS='=' read -r key val; do
              [[ "$key" =~ ^[[:space:]]*# ]] && continue
              [[ -z "$key" || "$key" =~ ^[[:space:]]*$ ]] && continue
              key=$(echo "$key" | xargs)
              envval="${!key}"
              [[ -z "$envval" ]] && envval="$val"
              echo "$key=$envval" >> "$out"
            done < "$file"
          done

      - name: Add to known hosts
        run: ssh-keyscan ${{ needs.terraform.outputs.aquila_ip }} >> /etc/ssh/ssh_known_hosts

      - name: Install dependencies
        run: ansible-galaxy install -r requirements.yaml

      - name: Run playbook
        run: ansible-playbook -u root -i inventory.ini playbook.yaml

  secrets:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: gliech/create-github-secret-action@v1
        with:
          location: medvesek
          name: AQUILA_IP
          value: ${{ needs.terraform.outputs.aquila_ip }}
          org_visibility: all
          pa_token: ${{ secrets.PA_TOKEN }}
