name: Deploy

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    outputs:
      aquila_ip: ${{ steps.output.outputs.aquila_ip }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Init
        run: terraform init

      - name: Apply
        run: terraform apply --auto-approve

      - name: Output
        id: output
        run: echo "aquila_ip=$(terraform output --raw instance_ip)" >> $GITHUB_OUTPUT

  ansible:
    needs: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE_GITHUB_ACTIONS }}
        
      - name: Install ansible
        run: sudo apt-get install -y ansible

      - name: Prepare inventory
        run: echo -e "[aquila]\n${{ needs.terraform.outputs.aquila_ip }}" > inventory.ini
      
      - name: Add to known hosts
        run: ssh-keyscan ${{ needs.terraform.outputs.aquila_ip }} >> /home/runner/.ssh/known_hosts

      - name: Run playbook
        run: ansible-playbook -u root -i inventory.ini playbook.yaml
