name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/**
      - .github/workflows/docker.yml

jobs:
  build:
    # Job name that shows in the GitHub UI
    name: Build Docker Images
    # Runner to use
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:docker/ansible-ci-image"
          push: true
          tags: ghcr.io/${{ github.repository }}-ansible:latest
